module.exports.descriptors = [
    'Kitty',
    'Black',
    'Cozy',
    'Academia',
    'Work',
    'Big University',
    'Big City',
    'Happy Dog',
    'Serene',
    'Study',
    'Quiet',
    'Cute',
    'Spacious',
    'Brew',
    'Madeline',
    'High',
    'Blend',
    'Warm'
]

module.exports.places = [
    'Cafe',
    'Library',
    'Lounge',
    'Bookshop',
    'Coffeshop',
    'Teashop',
    'Bookstore',
    'Space',
    'Bakery',
    'Teahouse',
    'Cafe and Bar',
    'Cafeteria',
    'Boutique',
    'Coffee Roasters',
    'Coffee',
    'Coffee and Bakery',
    'Kitchen',
    'Espresso',
    'Coffee & Tea',
    'Bar',
    'Garden'
]